# Generated by Django 4.0 on 2021-12-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_belongs_to_remove_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
