# Generated by Django 4.0 on 2021-12-11 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_remove_product_is_for_sale'),
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SiteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(auto_created=True, decimal_places=2, max_digits=8)),
                ('datetime', models.DateTimeField(auto_created=True, db_index=True, default=django.utils.timezone.now)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.sitetransactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('cart_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.sitetransaction')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
