# Generated by Django 4.0 on 2021-12-11 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetransaction',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
