# Generated by Django 4.0 on 2021-12-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_sitetransaction_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitetransaction',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.sitetransaction'),
        ),
    ]
