# Generated by Django 4.0 on 2021-12-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_discount_sitetransaction_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetransaction',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
