# Generated by Django 4.0 on 2021-12-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitetransaction',
            old_name='datetime',
            new_name='closed_at',
        ),
    ]
