# Generated by Django 4.0 on 2021-12-14 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_rename_datetime_sitetransaction_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='closed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
