# Generated by Django 4.0 on 2021-12-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_cart_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
