# Generated by Django 4.0 on 2021-12-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_cart_closed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='sitetransaction',
            name='is_sale',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.DeleteModel(
            name='SiteTransactionType',
        ),
    ]
