# Generated by Django 4.0 on 2021-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='if_for_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
