# Generated by Django 4.0 on 2021-12-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='desired_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
