# Generated by Django 4.0 on 2021-12-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_stock_desired_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='desired_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
