# Generated by Django 4.0 on 2021-12-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_for_sale',
        ),
    ]
