# Generated by Django 4.0 on 2021-12-14 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('stock', '0002_remove_stock_belongs_to_remove_stock_product'),
        ('products', '0009_remove_product_is_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=45, unique=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
