# Generated by Django 4.0 on 2021-12-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='belongs_to',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
