# Generated by Django 4.0 on 2021-12-14 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('products', '0016_alter_product_cost_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='belongs_to',
            field=models.ForeignKey(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
