# Generated by Django 4.0 on 2021-12-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_available_alter_stock_desired_amount'),
        ('products', '0019_alter_category_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock'),
        ),
    ]
